name: marvel_api_app
description: Marvel API App

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cached_network_image: ^2.5.0
  crypto: ^2.1.5
  cupertino_icons: ^1.0.0
  intl: ^0.16.1
  shared_preferences: ^0.5.12+4
  splashscreen: ^1.3.5

  flutter_localizations:
    sdk: flutter   

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/
    #Toda a pasta de assets é importada, para evitar ter que informar cada asset manualmente
